services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env    
    volumes:
      - ./:/home/node/app
    command: npm run dev
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:{PORT}']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
