ARG NODE_IMAGE=node:22-alpine

FROM $NODE_IMAGE AS base
RUN apk --no-cache add dumb-init python3 make g++ libc6-compat curl
RUN mkdir -p /home/node/app && chown node:node /home/node/app
WORKDIR /home/node/app
USER node
RUN mkdir tmp

FROM base AS dependencies
COPY --chown=node:node ./package*.json ./
RUN npm ci
RUN npm rebuild bcrypt --build-from-source
COPY --chown=node:node . .

FROM dependencies AS build
RUN node ace build --production

FROM base AS production
ENV NODE_ENV=production
ENV PORT=$API_PORT
ENV HOST=0.0.0.0
COPY --chown=node:node ./package*.json ./
RUN npm ci --production
COPY --chown=node:node --from=build /home/node/app/build .
EXPOSE $API_PORT
CMD [ "dumb-init", "node", "server.js" ]
